/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_UART_PB_H_INCLUDED
#define PB_UART_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) uartMessage_mac_t;
typedef PB_BYTES_ARRAY_T(33) uartMessage_ssid_t;
typedef PB_BYTES_ARRAY_T(3) uartMessage_country_t;
typedef struct _uartMessage {
    uartMessage_mac_t mac;
    uartMessage_ssid_t ssid;
    uint32_t channel;
    int32_t rssi;
    int32_t authmode;
    int32_t pairwise_cipher;
    int32_t groupwise_cipher;
    uartMessage_country_t country;
} uartMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define uartMessage_init_default                 {{0, {0}}, {0, {0}}, 0, 0, 0, 0, 0, {0, {0}}}
#define uartMessage_init_zero                    {{0, {0}}, {0, {0}}, 0, 0, 0, 0, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define uartMessage_mac_tag                      1
#define uartMessage_ssid_tag                     2
#define uartMessage_channel_tag                  3
#define uartMessage_rssi_tag                     4
#define uartMessage_authmode_tag                 5
#define uartMessage_pairwise_cipher_tag          6
#define uartMessage_groupwise_cipher_tag         7
#define uartMessage_country_tag                  8

/* Struct field encoding specification for nanopb */
#define uartMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    mac,               1) \
X(a, STATIC,   SINGULAR, BYTES,    ssid,              2) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           3) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              4) \
X(a, STATIC,   SINGULAR, INT32,    authmode,          5) \
X(a, STATIC,   SINGULAR, INT32,    pairwise_cipher,   6) \
X(a, STATIC,   SINGULAR, INT32,    groupwise_cipher,   7) \
X(a, STATIC,   SINGULAR, BYTES,    country,           8)
#define uartMessage_CALLBACK NULL
#define uartMessage_DEFAULT NULL

extern const pb_msgdesc_t uartMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define uartMessage_fields &uartMessage_msg

/* Maximum encoded size of messages (where known) */
#define UART_PB_H_MAX_SIZE                       uartMessage_size
#define uartMessage_size                         98

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
